# Força o Dev Services do Quarkus a usar a imagem do SQL Server 2019
quarkus.datasource.devservices.image-name=mcr.microsoft.com/mssql/server:2019-latest

# Aceita o EULA da Microsoft diretamente na inicialização do container do Quarkus
quarkus.datasource.devservices.container-env.ACCEPT_EULA=Y


quarkus.datasource.devservices.enabled=false
quarkus.datasource.jdbc=true
quarkus.datasource.db-kind=mssql

# Lembre-se de trocar o IP se o comando 'docker-machine ip' mostrar outro
quarkus.datasource.jdbc.url=jdbc:sqlserver://192.168.99.100:1433;encrypt=false

# Suas credenciais baseadas no comando docker run:
quarkus.datasource.username=sa
quarkus.datasource.password=Biontec#2026@

# Cria as tabelas automaticamente com base nas suas entidades Java
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true



